config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :restaurants do
    resources :reviews, only: [:new, :create, :edit, :update]
  end

  root 'restaurants#index'
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
  has_many :users, through: :reviews

  def average_point
    # 分子 = レストランにレビューを投稿したユーザーから、rateだけを抜き取って配列化し、足し上げている
    # 分母 = レストランにレビューを投稿したユーザーの数
    average = self.users.pluck(:rate).sum / self.users.count
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  has_many :reviews
  has_many :restaurants, through: :reviews

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    User.dummy_email(auth),
        password: Devise.friendly_token[0, 20]
      )
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurants, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_url(@restaurant)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_url(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(
      :name,
      :tel,
      :address,
      :url
    )
  end

  def set_restaurants
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :set_restaurant, only: [:new, :create, :edit, :update]

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(
      restaurant_id: params[:restaurant_id],
      user_id: current_user.id,
      title: review_params["title"],
      body: review_params["body"],
      rate: review_params["rate"].to_f
    )
    if @review.save
      redirect_to restaurant_url(@review.restaurant)
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(
      restaurant_id: params[:restaurant_id],
      user_id: current_user.id,
      title: review_params["title"],
      body: review_params["body"],
      rate: review_params["rate"].to_f
    )
      redirect_to restaurant_url(@review.restaurant)
    else
      render :edit
    end
  end

  private

  def review_params
    params.require(:review).permit(:title, :body, :rate)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  def twitter
    callback_from :twitter
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def make_star(rate)
    star = "★" * rate.round + "☆" * (5 - rate.round)
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "スパル食べログ", root_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse-menu">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "設定変更", edit_user_registration_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Facebookで登録",user_omniauth_authorize_path(:facebook) %></li>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_sidebar.html.erb
<%= link_to "新しくお店を登録する", new_restaurant_path, class: "btn btn-success btn-block" %>
<hr>

<% if current_user %>
  <div class="panel panel-default">
    <div class="panel-body">
      <div class="media">
        <div class="media-left">
          <img class="media-object" src="http://placehold.it/100x100">
        </div>
        <div class="media-body">
          <p>ようこそ <%= current_user.email %> さん</p>
          <p>口コミ：<%= current_user.reviews.count %>件</p>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    人気のお店
  </div>
 <!-- List group -->
  <ul class="list-group">
    <li class="list-group-item">Cras justo odio</li>
    <li class="list-group-item">Dapibus ac facilisis in</li>
    <li class="list-group-item">Morbi leo risus</li>
    <li class="list-group-item">Porta ac consectetur ac</li>
    <li class="list-group-item">Vestibulum at eros</li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpartaTabelog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>
<body>

<%= render partial: 'layouts/header' %>

<div class="container">
  <% if notice.present? %>
    <div class="alert alert-dismissable alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= notice %></p>
    </div>
  <% end %>

  <% if alert.present? %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= alert %></p>
    </div>
  <% end %>
  <%= yield %>

<div
  class="fb-like"
  data-share="true"
  data-width="450"
  data-show-faces="true">
</div>

</div>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, "店名" %><br>
    <%= f.text_field :name, class: 'form-controll' %>
  </div>
  <div class="form-group">
    <%= f.label :tel, "電話番号" %><br>
    <%= f.text_field :tel, class: 'form-controll' %>
  </div>
  <div class="form-group">
    <%= f.label :address, "住所" %><br>
    <%= f.text_field :address, class: 'form-controll' %>
  </div>
  <div class="form-group">
    <%= f.label :url, "ホームページ" %><br>
    <%= f.text_field :url, class: 'form-controll' %>
  </div>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>レストラン編集</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="row">
  <div class="col-lg-8">
    <h2>レストラン一覧</h2>
    <% @restaurants.each do |restaurant| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <strong><%= link_to restaurant.name, restaurant_path(restaurant) %></strong>
        <span class="text-muted pull-right"><%= restaurant.created_at.strftime('%Y/%m/%d') %></span>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-sm-2">
            <div class="thumbnail">
              <img class="img-responsive user-photo" src="http://image1-4.tabelog.k-img.com/restaurant/images/Rvw/37351/200x200_square_37351006.jpg">
            </div><!-- /thumbnail -->
          </div><!-- /col-sm-1 -->
          <div class="col-sm-10">
            <p><%# make_star(restaurant.average_point) %> <%# restaurant.average_point %>  ［ 口コミ <%= restaurant.reviews.count %>件 ］</p>
            <div class="panel panel-default">
              <div class="panel-body">
                <% restaurant.reviews.each do |review| %>
                  <p><%= review.title %> by <%= review.user.email %> (<%= review.user.reviews.count %>)</p>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div><!-- /panel-body -->
    </div>

    <% end %>
    <h2>新着口コミ</h2>
    <div class="row">
    <% Review.all.each do |review| %>
        <div class="col-sm-2">
          <div class="thumbnail">
            <img class="img-responsive user-photo" src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
          </div><!-- /thumbnail -->
        </div><!-- /col-sm-1 -->

        <div class="col-sm-10">
          <div class="panel panel-default">
            <div class="panel-heading">
              <strong><%= link_to review.title, restaurant_path(review.restaurant) %></strong>
              <span class="text-muted pull-right"><%= review.created_at.strftime('%Y/%m/%d') %></span>
            </div>
            <div class="panel-body">
              <p></p>
              <p><%= simple_format(review.body) %></p>
            </div><!-- /panel-body -->
          </div><!-- /panel panel-default -->
        </div><!-- /col-sm-5 -->
    <% end %>
      </div><!-- /row -->
  </div>

  <div class="col-lg-4">
    <%= render 'layouts/sidebar' %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>レストラン新規登録</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>
      <%= @restaurant.name %>
      <span class="pull-right"><%= @restaurant.tel %></span>
    </h1>
    <hr>
    <h2>
      <% if @restaurant.reviews.count >= 1 %>
        <b style="color:red;">
          <%= make_star(@restaurant.average_point) %>
          <%= @restaurant.average_point %>
        </b>
      <% else %>
        未評価
      <% end %>
    </h2>
    <% if user_signed_in? %>
      <% if current_user.reviews.where(restaurant_id: @restaurant.id).exists? %>
        <%= link_to "レビューを編集する", edit_restaurant_review_path(@restaurant, current_user), class: "btn btn-default" %>
      <% else %>
        <%= link_to "レビューを登録する", new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
      <% end %>
    <% else %>
      <%= link_to "ユーザー登録してレビューを投稿", new_user_registration_path, class: "btn btn-default" %>
    <% end %>
  </div>
</div>

<hr>

<div class="row">
  <div class="col-lg-8">
    <% @restaurant.reviews.each do |review| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title">
            <%= review.title %>
            <span class="pull-right">
              <small>訪問日：<%= review.created_at.strftime('%Y/%m/%d') %></small>
            </span>
          </h3>
        </div>
        <div class="panel-body">
          <div class="media">
            <div class="media-left">
                <img class="media-object" src="http://placehold.it/20x20">
            </div>
            <div class="media-body">
              <small>
                <%= review.user.email %> <b style="color:red;">(<%= review.user.reviews.count %>)</b> さんの口コミ<br>
                男性・東京都
              </small>
            </div>
          </div>
          <hr>
          <h5>
            <b style="color:red;"><%= make_star(review.rate) %> <%= review.rate %></b>
          </h5>
          <hr>
          <p><%= simple_format(review.body) %></p>
        </div>
        <div class="panel-footer">
          <small>利用規約に違反している口コミは、右のリンクから報告することができます。<a href="#">問題のある口コミを連絡する</a></small>
        </div>
      </div>
    <% end %>
    <div class="panel panel-default">
      <div class="panel-heading">店舗情報</div>
        <table class="table">
          <tr>
            <th>店名</th>
            <td><%= @restaurant.name %></td>
          </tr>
          <tr>
            <th>TEL・予約</th>
            <td><%= @restaurant.tel %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= @restaurant.address %></td>
          </tr>
          <tr>
            <th>ホームページ</th>
            <td><%= @restaurant.url %></td>
          </tr>
        </table>
      </div>
    </div>
  <div class="col-lg-4">
    <%= render 'layouts/sidebar' %>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= form_for([@restaurant, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div class="alert alert-danger">
      <p><b><%= @review.errors.count %>件のエラーがあります</b></p>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :rate, '点数' %><br>
    <%= f.select :rate, { "★☆☆☆☆" => 1, "★★☆☆☆" => 2,"★★★☆☆" => 3, "★★★★☆" => 4, "★★★★★" => 5 }, { prompt: true }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :title, '口コミのタイトル' %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :body, '口コミの内容' %><br>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/reviews/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>レビュー編集：<%= @restaurant.name %></h1>
    <%= render 'form' %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>レビュー作成：<%= @restaurant.name %></h1>
    <%= render 'form' %>
  </div>
</div>